version: '2'

services:
   proxy:
      image: jwilder/nginx-proxy
      networks:
         - general
      ports:
         - "80:80"
      volumes:
         - /var/run/docker.sock:/tmp/docker.sock
         - ./vhost.d:/etc/nginx/vhost.d
   phpmyadmin:
      build: phpmyadmin
      networks:
         - general
      environment:
         VIRTUAL_HOST: pma.docker
         PMA_SECRET: something_random
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
   portainer:
      networks:
         - general
      image: portainer/portainer
      command: -H unix:///var/run/docker.sock
      networks:
        - general
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - portainer_data:/data
      environment:
         VIRTUAL_HOST: portainer.docker
         VIRTUAL_PORT: 9000

volumes:
   portainer_data:

networks:
   general:
      external: true
